name: libphpx
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2 ]
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: embed, curl, redis
      - name: install dependencies
        run: sudo apt update -y && sudo apt install -y googletest libgtest-dev libboost-stacktrace-dev
      - name: Show machine information
        run: |
          date
          env
          uname -a
          ulimit -a
          php -v
          php --ini
          ls -al
          pwd
          echo "`git log -20 --pretty --oneline`"
          echo "`git log -10 --stat --pretty --oneline`"
      - name: build
        run: cmake . && make VERBOSE=1 -j$(nproc)
      - name: run tests
        run: cd tests && cmake . && make VERBOSE=1 -j$(nproc) && ./bin/phpx_tests
